"""Adding color collumn

Revision ID: a29080706884
Revises: 036efe3ea329
Create Date: 2023-09-01 15:30:02.558218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a29080706884"
down_revision: Union[str, None] = "036efe3ea329"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("color", sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "color")
    # ### end Alembic commands ###
